name: sign_dl
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cpuonly
  - python=3.7
  - pip
  - numpy
  - pip:
    - ipykernel
    - matplotlib
    - opencv-python
    - mediapipe
    - tqdm